load("@rules_rust//rust:defs.bzl", "rust_library")
package(default_visibility = ["//visibility:public"])

rust_library(
    name = "crypto",
    srcs = [
        "lib.rs",
        "hash.rs",
    ],
    deps = [
        "//baremetal/traits",
        "@crates_baremetal//:sha2",
        "@crates_baremetal//:sha3",
    ],
)
