load("@rules_rust//rust:defs.bzl", "rust_library")
package(default_visibility = ["//visibility:public"])

rust_library(
    name = "kmac",
    srcs = [
        "lib.rs",
        "driver.rs",
    ],
    deps = [
        "//registers:kmac",
        "//baremetal/traits",
        "//baremetal/base",
        "@ureg//:ureg",
        "@crates_baremetal//:ufmt",
    ],
)
